version: "3.4"
services:
  eth:
    restart: "${RESTART}"
    user: besu
    stop_grace_period: 3m
    image: hyperledger/besu
    volumes:
      - besu-eth-data:/opt/besu
    ports:
      - ${ETH_PORT}:${ETH_PORT}/tcp
      - ${ETH_PORT}:${ETH_PORT}/udp
    expose:
      - ${ETH_WS_PORT}/tcp
    entrypoint:
      - /opt/besu/bin/besu
      - --pruning-enabled
      - --p2p-port
      -  ${ETH_PORT}
      - --rpc-ws-enabled
      - --rpc-ws-api
      - "net,eth,web3"
      - --rpc-ws-host
      - 0.0.0.0
      - --rpc-ws-port
      - ${ETH_WS_PORT}
      - --host-allowlist=eth1,localhost
      - --logging
      - ${LOG_LEVEL}
      - --network
      - ${ETH_NETWORK}
  chainlink:
    depends_on:
      - eth
volumes:
  besu-eth-data:
