version: '3.4'
services:
  chainlink:
    restart: "${RESTART}"
    user: chainlink
    build:
      context: ./chainlink
      args:
        - USER=chainlink
        - DOCKER_TAG=${CHAIN_DOCKER_TAG}
    image: chainlink
    env_file: chainlink.env
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - ETH_CHAIN_ID=${NETWORK_ID}
      - LINK_CONTRACT_ADDRESS=${LINK_CONTRACT_ADDRESS}
      - ETH_URL=${ETH1_NODE}
      - ETH_SECONDARY_URLS=${ETH1_FAILOVER_NODE}
      - CHAINLINK_PORT=${CHAIN_PORT}
      - CHAINLINK_TLS_PORT=${CHAIN_TLS_PORT}
      - DATABASE_URL=${PGSQL_URL}
      - MINIMUM_CONTRACT_PAYMENT=${MIN_PAY}
      - ORACLE_CONTRACT_ADDRESS=${ORACLE_CONTRACT}
    ports:
      - ${CHAIN_PORT}:${CHAIN_PORT}/tcp
      - ${CHAIN_TLS_PORT}:${CHAIN_TLS_PORT}/tcp
    volumes:
      - chainlink-data:/var/lib/chainlink/
      - ./.secrets:/secrets
    entrypoint: wait-for-pgsql.sh ${PGSQL_URL} chainlink
    command: node start --password /secrets/wallet-password.txt --api /secrets/apicredentials.txt 
volumes:
  chainlink-data:
