version: '3.4'
services:
  chainlink:
    restart: ${RESTART}
    user: chainlink
    build:
      context: ./chainlink
      args:
        - USER=chainlink
        - DOCKER_TAG=${CHAIN_DOCKER_TAG}
    image: chainlink:local
    env_file: chainlink.env
    depends_on:
      - eth-proxy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - ETH_CHAIN_ID=${NETWORK_ID}
      - LINK_CONTRACT_ADDRESS=${LINK_CONTRACT_ADDRESS}
      - ETH_URL=ws://eth-proxy:4000/
      - CHAINLINK_PORT=${CHAIN_PORT}
      - CHAINLINK_TLS_PORT=${CHAIN_TLS_PORT}
      - DATABASE_URL=${PGSQL_URL}
      - MINIMUM_CONTRACT_PAYMENT=${MIN_PAY}
      - OPERATOR_CONTRACT_ADDRESS=${OPERATOR_CONTRACT}
    ports:
      - ${CHAIN_PORT}:${CHAIN_PORT}/tcp
      - ${CHAIN_TLS_PORT}:${CHAIN_TLS_PORT}/tcp
    volumes:
      - chainlink-data:/var/lib/chainlink/
      - ./.secrets:/secrets
    entrypoint: wait-for-pgsql.sh ${PGSQL_URL} chainlink
    command: node start --password /secrets/wallet-password.txt
  eth-proxy:
    restart: ${RESTART}
    image: fiews/cl-eth-failover
    volumes:
      - eth-proxy:/var/eth-proxy/
    entrypoint: /bin/sh -c "node index.js ${ETH_NODE_1} ${ETH_NODE_2} ${ETH_NODE_3} ${ETH_NODE_4} 2>&1 | tee /var/eth-proxy/eth-proxy.log"
volumes:
  chainlink-data:
  eth-proxy:
