version: "3.4"
services:
  eth:
    restart: "${RESTART}"
    user: geth
    build:
      context: ./geth
      dockerfile: ${GETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET} 
        - DOCKER_TAG=${GETH_DOCKER_TAG}
    stop_signal: SIGINT
    stop_grace_period: 3m
    image: geth_cl:local
    volumes:
      - geth-eth-data:/var/lib/goethereum
    ports:
      - ${ETH_PORT}:${ETH_PORT}/tcp
      - ${ETH_PORT}:${ETH_PORT}/udp
    expose:
      - ${ETH_WS_PORT}/tcp
    entrypoint:
      - geth
      - --nousb
      - --datadir
      - /var/lib/goethereum
      - --port
      - ${ETH_PORT}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${ETH_WS_PORT}
      - --ws.api
      - eth,net,web3
      - --${ETH_NETWORK}
  chainlink:
    depends_on:
      - eth
volumes:
  geth-eth-data:
