version: "3.4"
services:
  eth:
    restart: "${RESTART}"
    user: nethermind
    stop_grace_period: 3m
    build:
      context: ./nethermind
      dockerfile: Dockerfile.binary
      args:
        - BUILD_TARGET=${NM_SRC_BUILD_TARGET} 
        - DOCKER_TAG=${NM_DOCKER_TAG}
    image: nethermind_cl:local
    volumes:
      - nm-eth-data:/var/lib/nethermind
    ports:
      - ${ETH_PORT}:${ETH_PORT}/tcp
      - ${ETH_PORT}:${ETH_PORT}/udp
    expose:
      - ${ETH_WS_PORT}/tcp
      - ${ETH_RPC_PORT}/tcp
    entrypoint:
      - dotnet
      - /nethermind/Nethermind.Runner.dll
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.Host
      - 0.0.0.0
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net"
      - --JsonRpc.Port
      - ${ETH_RPC_PORT}
      - --JsonRpc.WebSocketsPort
      - ${ETH_WS_PORT}
      - --Network.DiscoveryPort
      -  ${ETH_PORT}
      - --Network.P2PPort
      -  ${ETH_PORT}
      - --Sync.FastSync
      - "true"
      - --config
      - ${ETH_NETWORK}
      - --Pruning.Enabled
      - "true"
      - --Pruning.CacheMb
      - "4096"
  chainlink:
    depends_on:
      - eth
volumes:
  nm-eth-data:
