ARG DOCKER_TAG=latest

FROM openethereum/openethereum:${DOCKER_TAG}

#Next is unused but included to avoid warnings
ARG BUILD_TARGET

ARG USER=openethereum

USER root

RUN cp /home/openethereum/openethereum /usr/local/bin

# Create data mount point with permissions
RUN mkdir -p /var/lib/openethereum && chown openethereum:openethereum /var/lib/openethereum && chmod 700 /var/lib/openethereum

# Use an unprivileged user.
USER ${USER}

WORKDIR /var/lib/openethereum

ENTRYPOINT ["openethereum"]
